[ClassVersion("1.0.0.0"), FriendlyName("cSelfSignedCert")]class cSelfSignedCert : OMI_BaseResource{     [Key] String Subject;     [Write, ValueMap{"CurrentUser","LocalMachine"}, Values{"CurrentUser","LocalMachine"}] String StoreLocation;     [Write, ValueMap{"TrustedPublisher","ClientAuthIssuer","Root","CA","AuthRoot","TrustedPeople","My","SmartCardRoot","Trust","Disallowed"}, Values{"TrustedPublisher","ClientAuthIssuer","Root","CA","AuthRoot","TrustedPeople","My","SmartCardRoot","Trust","Disallowed"}] String StoreName;     [Write, ValueMap{"Absent","Present"}, Values{"Absent","Present"}] String Ensure;};